x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  environment:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_metadata 
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config:/opt/airflow/config
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  # ==========================================
  # POSTGRESQL (DATABASE HOUSE)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" 
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql 
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # ==========================================
  # APACHE AIRFLOW COMPONENTS
  # ==========================================
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD:-admin}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_metadata 

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_metadata 
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # ==========================================
  # APACHE SUPERSET (BI LAYER)
  # ==========================================
  superset:
    image: apache/superset:4.0.1
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/superset_metadata
    volumes:
      - ./superset/superset_config.py:/app/superset_config.py
      - superset_home:/app/superset_home
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      superset-init:
        condition: service_completed_successfully
    
  superset-init:
    image: apache/superset:4.0.1
    container_name: superset_init
    environment:
      SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/superset_metadata
    volumes:
      - ./superset/superset_config.py:/app/superset_config.py
    entrypoint: /bin/sh
    command: >
      -c "
      superset db upgrade &&
      superset fab create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@admin.com &&
      superset init
      "
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  superset_home: